### ISSUE TITLE
Some feedback on plotnine/ggplot code simplification

### ISSUE THREAD

**Issue by krassowski** [jorvlan/open-visualizations#2]
This is very nice work, thank you very much for sharing this! I just noticed that some of the plots can be simplified a bit. Here is an example for Figure 6:

```python
violin_width = 0.2
violin_offset = 0.1

df = d.copy()
df['group'] = d.x.map({1: 'Before', 2: 'After'})
df['x'] = (d.x * 2 - 3) / 1.5
df['xj'] = (d.xj - 1.5)

colors = {'Before': 'dodgerblue', 'After': 'darkorange'}

fig6 = (
    ggplot(df, aes(x='x', y='y', group='group'))
    + geom_violin(
        aes(fill='group', x='x + x * violin_offset'),
        color='white', width=violin_width, alpha=.6
    )
    + geom_rect(
        aes(
            xmin='x - x * (violin_offset + violin_width)',
            xmax='x + x * violin_offset',
            ymin='min(y)', ymax='max(y)'
        ),
        fill='white'
    )
    + geom_boxplot(aes(x='x', fill='group'), width=.05, alpha=.6)
    + geom_point(aes(x='xj', color='group'), alpha=.6, size=2)
    + geom_line(df, aes(x='xj', group='id'), color='lightgray', alpha=.5)
    + theme_classic()
    + scale_x_continuous(
        breaks=sorted(df.x.unique()), labels=labels,
        expand=[0, 0.25], name='Conditions'
    )
    + scale_color_manual(values=colors, guide=False)
    + scale_fill_manual(values=colors, guide=False)
    + ylab('Value')
    + ggtitle('Figure 6: repeated measures grouped by color with box- and violinplots')
)
```

![image](https://user-images.githubusercontent.com/5832902/77863325-61df6280-7219-11ea-8650-542a837a451b.png)

I know that this is not necessarily a better approach, just different. Hope that it might inspire someone/show that plotnine/ggplot way can be even more concise!

**Comment by jorvlan** [comment]
Code simplifications are always welcome!

With your permission, I could try to add this improvement in the next version.
And in the README.md, could add your name to a list of people that made suggestions for code improvements.

Thanks for sharing.

**Comment by krassowski** [comment]
Sure, I am happy for you to use this/modify/draw upon!

Just of note, the above example uses a small workaround with `scale_x_continuous` (it always works for me as a last resort measure if I cannot easliy get what I want with a discrete scale).
