### ISSUE TITLE
Figure10-Python

### ISSUE THREAD

**Issue by ghost** [jorvlan/open-visualizations#3]
Hi, thanks a lot for sharing this is great I felt the vizualizations  you create are very effective. I just noticed that the generation of the Figure10 in the main Readme.md generated with Python is not available in the notebook.

**Comment by jorvlan** [comment]
Hi, thanks for your feedback. That is correct, but you can find the code in issue #2 in my repository. I will update my tutorials with that code in the upcoming period.

**Comment by ghost** [comment]
Thanks I missed this!
