### ISSUE TITLE
Error in geom_half_boxplot

### ISSUE THREAD

**Issue by annagasa** [jorvlan/open-visualizations#5]
Hi, 

I am working with the code in figure 5b but it gives error when I run the boxplot part, specifically first part of the code: geom_half_boxplot(data = d %>% filter(x=="1")). The specific error is: **Error in data.frame(color = data$color, linewidth = data$linewidth, : arguments imply a different number of rows: 1, 0"_.** The rest of the code in the figure works fine (geom_point, geom_line, geom_half_violin). Do you know why this error occurs and how can I fix it? 

Thank you very much, 

Anna

**Comment by jorvlan** [comment]
Please update gghalves to its newest version, this will most likely fix it

**Comment by annagasa** [comment]
Hi, thanks for your help but the error is still there although having
updated gghalves. Do you know any other possible solutions?

Thank you in advance,

Anna
